name: Deploy Rakshak to Firebase
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Frontend Dependencies
        run: npm ci
      - name: Build Frontend
        run: npm run build
      - name: Install Backend Dependencies
        working-directory: ./functions
        run: npm ci
      - name: Deploy to Firebase
        uses: wix/firebase-action@v3.0.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
